version: 2
jobs:
  build-and-test:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          PROJECT_NAME: cfc-production
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image and Run Tests
          command: |
            echo $CIRCLE_BUILD_NUM > BUILD
            docker build . -t gcr.io/$PROJECT_NAME/heimdall:$CIRCLE_BUILD_NUM
      - run:
          name: Save build
          command: |
            mkdir -p /tmp/heimdall/docker-images/
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo Saving build and build tag for master branch.
              cp ./BUILD /tmp/heimdall/docker-images/BUILD
              docker save -o /tmp/heimdall/docker-images/heimdall.tar gcr.io/$PROJECT_NAME/heimdall:$CIRCLE_BUILD_NUM
            else
              echo Not saving build for development branch.
            fi
      - persist_to_workspace:
          root: /tmp/heimdall
          paths:
            - docker-images
  deploy:
    docker:
      - image: google/cloud-sdk:latest
        environment:
          PROJECT_NAME: cfc-production
          PROJECT_ID: cfc-production
          CLUSTER_NAME: heimdall
          CLOUDSDK_COMPUTE_ZONE: us-east4-c
    steps:
      - attach_workspace:
          at: /tmp/heimdall
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/heimdall/docker-images/heimdall.tar
      - run:
          name: Set up GCP
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud --quiet auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $PROJECT_ID
            gcloud --quiet config set container/cluster $CLUSTER_NAME
            gcloud --quiet container clusters get-credentials $CLUSTER_NAME
            gcloud --quiet auth configure-docker
      - run:
          name: Push and Deploy Docker Image
          command: |
            export BUILD_TAG=`cat /tmp/heimdall/docker-images/BUILD`
            docker push gcr.io/${PROJECT_NAME}/heimdall:$BUILD_TAG
            bash infrastructure/kube/thesis-ops/update-image.sh $BUILD_TAG
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
