version: 2.1
executors:
  docker-git:
    docker:
      - image: docker:18.06.0-ce-git
  docker-gcloud-cli:
    docker:
      - image: google/cloud-sdk:slim
  docker-node:
    docker:
      - image: circleci/node:11
  docker-thesis-buildpack:
    docker:
      - image: thesisco/docker-buildpack:bionic

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
  gcp-cli: circleci/gcp-cli@1.8.2

jobs:
  build-and-test:
    executor: docker-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image and Run Tests
          # Note: Tests are run from the Dockerfile
          command: |
            echo $CIRCLE_BUILD_NUM > BUILD
            docker build . -f infrastructure/docker/Dockerfile -t $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/heimdall:$CIRCLE_BUILD_NUM
      - run:
          name: Save build
          command: |
            echo Saving build and build tag.
            mkdir -p /tmp/heimdall/docker-images/
            cp ./BUILD /tmp/heimdall/docker-images/BUILD
            docker save -o /tmp/heimdall/docker-images/heimdall.tar $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/heimdall:$CIRCLE_BUILD_NUM
      - persist_to_workspace:
          root: /tmp/heimdall
          paths:
            - docker-images
  publish-docker-image:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/heimdall
      - gcp-gcr/gcr-auth:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - run:
          name: Load and Push Docker image
          command: |
            export BUILD_TAG=`cat /tmp/heimdall/docker-images/BUILD`
            docker load -i /tmp/heimdall/docker-images/heimdall.tar
            docker push $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/heimdall:$BUILD_TAG
  deploy:
    executor: docker-thesis-buildpack
    steps:
      - attach_workspace:
          at: /tmp/heimdall
      - checkout
      - run:
          name: Set Gcloud Auth
          command: |
            echo $GCLOUD_SERVICE_KEY_JUMPHOST_SSH > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Deploy Docker Image
          command: |
            export BUILD_TAG=`cat /tmp/heimdall/docker-images/BUILD`
            bash infrastructure/kube/thesis-ops/update-image.sh $BUILD_TAG
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          context: thesis-ops
      - publish-docker-image:
          context: thesis-ops
          filters:
            branches:
              only: master
          requires:
            - build-and-test
      - deploy:
          context: thesis-ops
          filters:
            branches:
              only: master
          requires:
            - publish-docker-image
